### ISSUE TITLE
Set same "migrator" address for pair contracts as factory has

### ISSUE THREAD

**Issue by alpe** [confio/tfi#71]
Currently none is set
https://github.com/confio/tfi/blob/main/contracts/tfi-factory/src/contract.rs#L152

**Comment by maurolacy** [comment]
I think this must be addressed in the tgrade-app repo. In the scripts that store those contracts in the chain.

**Comment by alpe** [comment]
No, this is not related to the setup in tgrade-app. The tfi factory creates a new contract instances for each pair. See link above.

**Comment by maurolacy** [comment]
I see, you are right. We can just set the same admin the tfi contract has. Will do.
